INSERT INTO MEMBER VALUES(1,'USER','kim','010','abc@naver.com','yeonsu','1234');
INSERT INTO MEMBER VALUES(2,'ADMIN','kim2','010','abc@naver.com','yeonsu','1234');

INSERT INTO BOARD VALUES(98,0,2,now(),now(),'NOTICE','kim2','NOTICE1','NOTIFICATION');
INSERT INTO BOARD VALUES(99,0,2,now(),now(),'NOTICE','kim2','NOTICE2','NOTIFICATION');



