INSERT INTO MEMBER VALUES(1,'USER','kim','010','abc@naver.com','yeonsu','1234');
INSERT INTO MEMBER VALUES(2,'ADMIN','kim2','010','abc@naver.com','yeonsu','1234');
INSERT INTO BOARD VALUES(1,0,2,now(),now(),'NOTICE','kim2','NOTICE1','NOTIFICATION');
INSERT INTO BOARD VALUES(2,0,1,now(),now(),'POST','kim2','POST1','COMMONPOST');
INSERT INTO BOARD VALUES(3,0,2,now(),now(),'NOTICE','kim2','NOTICE2','NOTIFICATION');
INSERT INTO BOARD VALUES(4,0,1,now(),now(),'POST','kim2','POST2','COMMONPOST');
INSERT INTO BOARD VALUES(6,0,1,now(),now(),'POST','kim2','POST3','COMMONPOST');
INSERT INTO BOARD VALUES(8,0,1,now(),now(),'POST','kim2','POST4','COMMONPOST');
INSERT INTO BOARD VALUES(10,0,1,now(),now(),'POST','kim2','POST6','COMMONPOST');


